name: Docker Build

on:
  workflow_call:
    inputs:
      ns:
        description: "Docker organization or namespace"
        required: true
        type: string
      repo:
        description: "Docker repository name"
        required: true
        type: string
      username:
        description: "Username for Docker registry authentication"
        required: true
        type: string
      file:
        description: "Path to Dockerfile to use for building the image"
        required: false
        type: string
        default: ./Dockerfile
      runner-amd64:
        description: "Runner label to use for amd64 builds"
        required: false
        type: string
        default: ubuntu-24.04
      runner-arm64:
        description: "Runner label to use for arm64 builds"
        required: false
        type: string
        default: ubuntu-24.04-arm
    secrets:
      password:
        description: "Password or token for Docker registry authentication"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]

    runs-on: ${{ matrix.arch == 'arm64' && inputs.runner-arm64 || inputs.runner-amd64 }}

    outputs:
      digest-amd64: ${{ steps.digest.outputs.digest-amd64 }}
      digest-arm64: ${{ steps.digest.outputs.digest-arm64 }}
      repo-path: ${{ steps.docker-vars.outputs.repo-path }}

    steps:
      - id: docker-vars
        uses: zrbecker/github-ci/actions/docker-vars@main
        with:
          ns: ${{ inputs.ns }}
          repo: ${{ inputs.repo }}
          tag-suffix: "-${{ matrix.arch }}"

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - uses: docker/setup-buildx-action@v3

      - id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.arch }}
          context: .
          file: ${{ inputs.file }}
          push: true
          tags: ${{ steps.docker-vars.outputs.refs }}

      - id: digest
        run: echo "digest-${{ matrix.arch }}=${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"

  merge-images:
    runs-on: ubuntu-latest
    needs: [build-images]
    steps:
      - id: docker-vars
        uses: zrbecker/github-ci/actions/docker-vars@main
        with:
          ns: ${{ inputs.ns }}
          repo: ${{ inputs.repo }}

      - uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - run: |
          docker buildx imagetools create \
            ${{ steps.docker-vars.outputs.tag-args }} \
            ${{ needs.build-images.outputs.repo-path }}@${{ needs.build-images.outputs.digest-amd64 }} \
            ${{ needs.build-images.outputs.repo-path }}@${{ needs.build-images.outputs.digest-arm64 }}
