on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - id: docker-vars
        uses: zrbecker/github-ci/actions/docker-vars@main
        with:
          docker-ns: zrbecker
          docker-repo: hellohttp
          docker-tag-suffix: "-arm64"
          docker-tag-branch-prefix: "branch-"
