on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: docker-vars
        uses: ./actions/docker-vars
        with:
          docker-ns: zrbecker
          docker-repo: hellohttp
          docker-tag-suffix: "-arm64"
          docker-tag-branch-prefix: "branch-"
