name: Docker Variables
description: Generate and export Docker tag variables

inputs:
  docker-ns:
    description: "Docker organization or namespace"
    required: true
  docker-repo:
    description: "Repository name for the Docker image"
    required: true
  docker-tag-prefix:
    description: "Optional prefix for the Docker tag"
    required: false
  docker-tag-suffix:
    description: "Optional suffix for the Docker tag"
    required: false
  docker-tag-branch-prefix:
    description: "Optional prefix to apply when generating a Docker tag from a branch name"
    required: false
  docker-tag-branch-suffix:
    description: "Optional suffix to apply when generating a Docker tag from a branch name"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/docker_vars.sh >> "$GITHUB_ENV"
        ${{ github.action_path }}/docker_vars.sh >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        DOCKER_NS: ${{ inputs.docker-ns }}
        DOCKER_REPO: ${{ inputs.docker-repo }}
        DOCKER_TAG_SUFFIX: ${{ inputs.docker-tag-suffix }}
        DOCKER_TAG_PREFIX: ${{ inputs.docker-tag-prefix }}
        DOCKER_TAG_BRANCH_PREFIX: ${{ inputs.docker-tag-branch-prefix }}
        DOCKER_TAG_BRANCH_SUFFIX: ${{ inputs.docker-tag-branch-suffix }}
