on:
  workflow_dispatch:

jobs:
  go-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run Go version check
        run: go version
